
BASE_LOCATION_ID = 12905168
LOCATION_MAPPING = {
	[BASE_LOCATION_ID + 0000000] = { { "@Tutorial/Tutorial Complete" } },
	[BASE_LOCATION_ID + 0000001] = { { "@Tutorial/Tutorial Coin" } },

	[BASE_LOCATION_ID + 0000003] = { { "@The Root Pack/The Root Pack Complete/" } },
	[BASE_LOCATION_ID + 0000005] = { { "@Goopy Le Grande/Goopy Le Grande Complete/" } },
	[BASE_LOCATION_ID + 0000007] = { { "@Ribby And Croaks/Ribby And Croaks Complete/" } },
	[BASE_LOCATION_ID + 0000009] = { { "@Cagney Carnation/Cagney Carnation Complete/" } },
	[BASE_LOCATION_ID + 0000011] = { { "@Baroness Von Bon Bon/Baroness Von Bon Bon Complete/" } },
	[BASE_LOCATION_ID + 0000013] = { { "@Beppi The Clown/Beppi The Clown Complete/" } },
	[BASE_LOCATION_ID + 0000015] = { { "@Grim Matchstick/Grim Matchstick Complete/" } },
	[BASE_LOCATION_ID + 0000017] = { { "@Rumor Honeybottoms/Rumor Honeybottoms Complete/" } },
	[BASE_LOCATION_ID + 0000019] = { { "@Captain Brineybeard/Captain Brineybeard Complete/" } },
	[BASE_LOCATION_ID + 0000021] = { { "@Werner Werman/Werner Werman Complete/" } },
	[BASE_LOCATION_ID + 0000023] = { { "@Sally Stageplay/Sally Stageplay Complete/" } },
	[BASE_LOCATION_ID + 0000025] = { { "@Phantom Express/Phantom Express Complete/" } },
	[BASE_LOCATION_ID + 0000027] = { { "@King Dice/King Dice Complete/" } },
	[BASE_LOCATION_ID + 0000029] = { { "@Hilda Berg/Hilda Berg Complete/" } },
	[BASE_LOCATION_ID + 0000031] = { { "@Djimmi The Great/Djimmi The Great Complete/" } },
	[BASE_LOCATION_ID + 0000033] = { { "@Wally Warbles/Wally Warbles Complete/" } },
	[BASE_LOCATION_ID + 0000035] = { { "@Cala Maria/Cala Maria Complete/" } },
	[BASE_LOCATION_ID + 0000037] = { { "@Dr. Kahl's Robot/Dr. Kahl's Robot Complete/" } },

	[BASE_LOCATION_ID + 0000004] = { { "@The Root Pack/The Root Pack Top Grade/" } },
	[BASE_LOCATION_ID + 0000006] = { { "@Goopy Le Grande/Goopy Le Grande Top Grade/" } },
	[BASE_LOCATION_ID + 0000008] = { { "@Ribby And Croaks/Ribby And Croaks Top Grade/" } },
	[BASE_LOCATION_ID + 0000010] = { { "@Cagney Carnation/Cagney Carnation Top Grade/" } },
	[BASE_LOCATION_ID + 0000012] = { { "@Baroness Von Bon Bon/Baroness Von Bon Bon Top Grade/" } },
	[BASE_LOCATION_ID + 0000014] = { { "@Beppi The Clown/Beppi The Clown Top Grade/" } },
	[BASE_LOCATION_ID + 0000016] = { { "@Grim Matchstick/Grim Matchstick Top Grade/" } },
	[BASE_LOCATION_ID + 0000018] = { { "@Rumor Honeybottoms/Rumor Honeybottoms Top Grade/" } },
	[BASE_LOCATION_ID + 0000020] = { { "@Captain Brineybeard/Captain Brineybeard Top Grade/" } },
	[BASE_LOCATION_ID + 0000022] = { { "@Werner Werman/Werner Werman Top Grade/" } },
	[BASE_LOCATION_ID + 0000024] = { { "@Sally Stageplay/Sally Stageplay Top Grade/" } },
	[BASE_LOCATION_ID + 0000026] = { { "@Phantom Express/Phantom Express Top Grade/" } },
	[BASE_LOCATION_ID + 0000028] = { { "@King Dice/King Dice Top Grade/" } },
	[BASE_LOCATION_ID + 0000030] = { { "@Hilda Berg/Hilda Berg Top Grade/" } },
	[BASE_LOCATION_ID + 0000032] = { { "@Djimmi The Great/Djimmi The Great Top Grade/" } },
	[BASE_LOCATION_ID + 0000034] = { { "@Wally Warbles/Wally Warbles Top Grade/" } },
	[BASE_LOCATION_ID + 0000036] = { { "@Cala Maria/Cala Maria Top Grade/" } },
	[BASE_LOCATION_ID + 0000038] = { { "@Dr. Kahl's Robot/Dr. Kahl's Robot Top Grade/" } },

	[BASE_LOCATION_ID + 0000125] = { { "@The Root Pack/The Root Pack Secret Complete/" } },
	[BASE_LOCATION_ID + 0000126] = { { "@Djimmi The Great/Djimmi The Great Secret Complete/" } },
	[BASE_LOCATION_ID + 0000127] = { { "@Sally Stageplay/Sally Stageplay Secret Complete/" } },

	[BASE_LOCATION_ID + 0000050] = { { "@Forest Follies/Forest Follies Complete/" } },
	[BASE_LOCATION_ID + 0000053] = { { "@Forest Follies/Forest Follies Coin 1/" } },
	[BASE_LOCATION_ID + 0000054] = { { "@Forest Follies/Forest Follies Coin 2/" } },
	[BASE_LOCATION_ID + 0000055] = { { "@Forest Follies/Forest Follies Coin 3/" } },
	[BASE_LOCATION_ID + 0000056] = { { "@Forest Follies/Forest Follies Coin 4/" } },
	[BASE_LOCATION_ID + 0000057] = { { "@Forest Follies/Forest Follies Coin 5/" } },

	[BASE_LOCATION_ID + 0000058] = { { "@Treetop Trouble/Treetop Trouble Complete/" } },
	[BASE_LOCATION_ID + 0000061] = { { "@Treetop Trouble/Treetop Trouble Coin 1/" } },
	[BASE_LOCATION_ID + 0000062] = { { "@Treetop Trouble/Treetop Trouble Coin 2/" } },
	[BASE_LOCATION_ID + 0000063] = { { "@Treetop Trouble/Treetop Trouble Coin 3/" } },
	[BASE_LOCATION_ID + 0000064] = { { "@Treetop Trouble/Treetop Trouble Coin 4/" } },
	[BASE_LOCATION_ID + 0000065] = { { "@Treetop Trouble/Treetop Trouble Coin 5/" } },

	[BASE_LOCATION_ID + 0000066] = { { "@Funfair Fever/Funfair Fever Complete/" } },
	[BASE_LOCATION_ID + 0000069] = { { "@Funfair Fever/Funfair Fever Coin 1/" } },
	[BASE_LOCATION_ID + 0000070] = { { "@Funfair Fever/Funfair Fever Coin 2/" } },
	[BASE_LOCATION_ID + 0000071] = { { "@Funfair Fever/Funfair Fever Coin 3/" } },
	[BASE_LOCATION_ID + 0000072] = { { "@Funfair Fever/Funfair Fever Coin 4/" } },
	[BASE_LOCATION_ID + 0000073] = { { "@Funfair Fever/Funfair Fever Coin 5/" } },

	[BASE_LOCATION_ID + 0000074] = { { "@Funhouse Frazzle/Funhouse Frazzle Complete/" } },
	[BASE_LOCATION_ID + 0000077] = { { "@Funhouse Frazzle/Funhouse Frazzle Coin 1/" } },
	[BASE_LOCATION_ID + 0000078] = { { "@Funhouse Frazzle/Funhouse Frazzle Coin 2/" } },
	[BASE_LOCATION_ID + 0000079] = { { "@Funhouse Frazzle/Funhouse Frazzle Coin 3/" } },
	[BASE_LOCATION_ID + 0000080] = { { "@Funhouse Frazzle/Funhouse Frazzle Coin 4/" } },
	[BASE_LOCATION_ID + 0000081] = { { "@Funhouse Frazzle/Funhouse Frazzle Coin 5/" } },

	[BASE_LOCATION_ID + 0000082] = { { "@Perilous Piers/Perilous Piers Complete/" } },
	[BASE_LOCATION_ID + 0000085] = { { "@Perilous Piers/Perilous Piers Coin 1/" } },
	[BASE_LOCATION_ID + 0000086] = { { "@Perilous Piers/Perilous Piers Coin 2/" } },
	[BASE_LOCATION_ID + 0000087] = { { "@Perilous Piers/Perilous Piers Coin 3/" } },
	[BASE_LOCATION_ID + 0000088] = { { "@Perilous Piers/Perilous Piers Coin 4/" } },
	[BASE_LOCATION_ID + 0000089] = { { "@Perilous Piers/Perilous Piers Coin 5/" } },

	[BASE_LOCATION_ID + 0000090] = { { "@Rugged Ridge/Rugged Ridge Complete/" } },
	[BASE_LOCATION_ID + 0000093] = { { "@Rugged Ridge/Rugged Ridge Coin 1/" } },
	[BASE_LOCATION_ID + 0000094] = { { "@Rugged Ridge/Rugged Ridge Coin 2/" } },
	[BASE_LOCATION_ID + 0000095] = { { "@Rugged Ridge/Rugged Ridge Coin 3/" } },
	[BASE_LOCATION_ID + 0000096] = { { "@Rugged Ridge/Rugged Ridge Coin 4/" } },
	[BASE_LOCATION_ID + 0000097] = { { "@Rugged Ridge/Rugged Ridge Coin 5/" } },

	[BASE_LOCATION_ID + 0000051] = { { "@Forest Follies/Forest Follies Top Grade/" } },
	[BASE_LOCATION_ID + 0000052] = { { "@Forest Follies/Forest Follies Top Grade/" } },
	[BASE_LOCATION_ID + 0000059] = { { "@Treetop Trouble/Treetop Trouble Top Grade/" } },
	[BASE_LOCATION_ID + 0000060] = { { "@Treetop Trouble/Treetop Trouble Top Grade/" } },
	[BASE_LOCATION_ID + 0000067] = { { "@Funfair Fever/Funfair Fever Top Grade/" } },
	[BASE_LOCATION_ID + 0000068] = { { "@Funfair Fever/Funfair Fever Top Grade/" } },
	[BASE_LOCATION_ID + 0000075] = { { "@Funhouse Frazzle/Funhouse Frazzle Top Grade/" } },
	[BASE_LOCATION_ID + 0000076] = { { "@Funhouse Frazzle/Funhouse Frazzle Top Grade/" } },
	[BASE_LOCATION_ID + 0000083] = { { "@Perilous Piers/Perilous Piers Top Grade/" } },
	[BASE_LOCATION_ID + 0000084] = { { "@Perilous Piers/Perilous Piers Top Grade/" } },
	[BASE_LOCATION_ID + 0000091] = { { "@Rugged Ridge/Rugged Ridge Top Grade/" } },
	[BASE_LOCATION_ID + 0000092] = { { "@Rugged Ridge/Rugged Ridge Top Grade/" } },

	[BASE_LOCATION_ID + 0000098] = { { "@Mausoleum I/" } },
	[BASE_LOCATION_ID + 0000099] = { { "@Mausoleum II/" } },
	[BASE_LOCATION_ID + 00000100] = { { "@Mausoleum III/" } },

	[BASE_LOCATION_ID + 00000114] = { { "@Isle 1 Secret Coin/" } },
	[BASE_LOCATION_ID + 00000115] = { { "@Isle 2 Secret Coin/" } },
	[BASE_LOCATION_ID + 00000116] = { { "@Isle 3 Secret Coin/" } },
	[BASE_LOCATION_ID + 00000117] = { { "@Inkwell Hell Secret Coin/" } },
	[BASE_LOCATION_ID + 00000112] = { { "@Mac's Coins/" } },
	[BASE_LOCATION_ID + 00000113] = { { "@Talk To Canteen Hughes/" } },
	[BASE_LOCATION_ID + 00000118] = { { "@Buster Quest/" } },
	[BASE_LOCATION_ID + 00000119] = { { "@Ginger Quest/" } },
	[BASE_LOCATION_ID + 00000120] = { { "@Barbershop Quartet Quest/" } },
	[BASE_LOCATION_ID + 00000121] = { { "@Pacifist Quest/" } },
	[BASE_LOCATION_ID + 00000122] = { { "@Silverworth Quest/" } },

	[BASE_LOCATION_ID + 00000101] = { { "@Shop Weapon 1/" } },
	[BASE_LOCATION_ID + 00000102] = { { "@Shop Weapon 2/" } },
	[BASE_LOCATION_ID + 00000103] = { { "@Shop Weapon 3/" } },
	[BASE_LOCATION_ID + 00000104] = { { "@Shop Weapon 4/" } },
	[BASE_LOCATION_ID + 00000105] = { { "@Shop Weapon 5/" } },
	[BASE_LOCATION_ID + 00000106] = { { "@Shop Charm 1/" } },
	[BASE_LOCATION_ID + 00000107] = { { "@Shop Charm 2/" } },
	[BASE_LOCATION_ID + 00000108] = { { "@Shop Charm 3/" } },
	[BASE_LOCATION_ID + 00000109] = { { "@Shop Charm 4/" } },
	[BASE_LOCATION_ID + 00000110] = { { "@Shop Charm 5/" } },
	[BASE_LOCATION_ID + 00000111] = { { "@Shop Charm 6/" } },
	
}